# Turso Edge Computing Deployment Configuration
# Defines edge regions, replication strategies, and performance targets

edge_deployment:
  name: turso-edge-global
  version: 1.0.0
  
  # Primary region configuration
  primary_region:
    id: us-west-2
    endpoint: wss://us-west-2.turso.io
    role: primary
    capacity:
      max_connections: 10000
      max_requests_per_second: 50000
      storage_gb: 1000
    
  # Edge regions
  edge_regions:
    - id: us-east-1
      name: US East (Virginia)
      endpoint: wss://us-east-1.turso.io
      priority: 1
      capacity:
        max_connections: 5000
        max_requests_per_second: 25000
        storage_gb: 500
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 1000
        
    - id: eu-central-1
      name: EU Central (Frankfurt)
      endpoint: wss://eu-central-1.turso.io
      priority: 2
      capacity:
        max_connections: 5000
        max_requests_per_second: 25000
        storage_gb: 500
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 2000
        
    - id: eu-west-1
      name: EU West (Ireland)
      endpoint: wss://eu-west-1.turso.io
      priority: 2
      capacity:
        max_connections: 3000
        max_requests_per_second: 15000
        storage_gb: 300
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 2000
        
    - id: ap-southeast-1
      name: Asia Pacific (Singapore)
      endpoint: wss://ap-southeast-1.turso.io
      priority: 3
      capacity:
        max_connections: 5000
        max_requests_per_second: 25000
        storage_gb: 500
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 3000
        
    - id: ap-northeast-1
      name: Asia Pacific (Tokyo)
      endpoint: wss://ap-northeast-1.turso.io
      priority: 3
      capacity:
        max_connections: 3000
        max_requests_per_second: 15000
        storage_gb: 300
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 3000
        
    - id: sa-east-1
      name: South America (São Paulo)
      endpoint: wss://sa-east-1.turso.io
      priority: 4
      capacity:
        max_connections: 2000
        max_requests_per_second: 10000
        storage_gb: 200
      replication:
        from_primary: true
        mode: async
        max_lag_ms: 5000

# Replication configuration
replication:
  default_consistency: eventual
  conflict_resolution: version_vector
  sync_interval_ms: 1000
  batch_size: 1000
  compression: true
  encryption: true
  
  # Consistency levels by operation
  consistency_levels:
    - operation: write
      level: strong
      regions: [primary]
      
    - operation: read
      level: eventual
      regions: all
      
    - operation: transaction
      level: strong
      regions: [primary, replicas]

# Query routing configuration
query_routing:
  strategy: latency_optimized
  cache:
    enabled: true
    ttl_seconds: 300
    max_size_mb: 1024
    
  load_balancing:
    algorithm: weighted_round_robin
    health_check_interval_ms: 5000
    failover_threshold_ms: 1000
    
  locality:
    enabled: true
    weight: 0.6
    data_distribution_tracking: true

# Session management configuration
session_management:
  storage:
    ttl_seconds: 3600
    max_size_kb: 64
    compression: true
    encryption: true
    
  replication:
    mode: async
    priority_regions: [us-west-2, eu-central-1]
    
  migration:
    enabled: true
    threshold_accesses: 3
    time_window_seconds: 300

# Real-time sync configuration
real_time_sync:
  enabled: true
  transport: websocket
  
  websocket:
    heartbeat_interval_ms: 30000
    reconnect_delay_ms: 1000
    max_reconnect_attempts: 5
    
  batching:
    enabled: true
    max_batch_size: 100
    batch_timeout_ms: 100
    
  compression:
    enabled: true
    threshold_bytes: 1024
    algorithm: zstd

# CRDT configuration
crdt:
  enabled: true
  types:
    - g-counter
    - pn-counter
    - or-set
    - lww-register
    
  conflict_resolution:
    strategy: automatic
    log_conflicts: true
    
  garbage_collection:
    enabled: true
    interval_seconds: 3600
    tombstone_ttl_seconds: 86400

# Performance targets
performance_targets:
  latency:
    p50_ms: 10
    p95_ms: 50
    p99_ms: 100
    
  throughput:
    reads_per_second: 100000
    writes_per_second: 10000
    
  availability:
    target_percent: 99.99
    
  consistency:
    replication_lag_p95_ms: 1000
    conflict_rate_percent: 0.1

# Monitoring configuration
monitoring:
  metrics:
    enabled: true
    interval_seconds: 60
    retention_days: 30
    
  alerts:
    - name: high_latency
      condition: latency_p95 > 100
      severity: warning
      
    - name: replication_lag
      condition: replication_lag > 5000
      severity: critical
      
    - name: high_error_rate
      condition: error_rate > 0.01
      severity: critical
      
  dashboards:
    - name: edge_performance
      refresh_seconds: 30
      
    - name: replication_status
      refresh_seconds: 60
      
    - name: session_analytics
      refresh_seconds: 300

# Security configuration
security:
  authentication:
    method: jwt
    token_ttl_seconds: 3600
    
  encryption:
    at_rest: true
    in_transit: true
    algorithm: aes-256-gcm
    
  access_control:
    enabled: true
    default_policy: deny
    
  audit_logging:
    enabled: true
    retention_days: 90

# Deployment configuration
deployment:
  strategy: blue_green
  
  rollout:
    canary_percent: 10
    validation_time_minutes: 30
    automatic_rollback: true
    
  health_checks:
    startup:
      path: /health/startup
      timeout_seconds: 30
      
    liveness:
      path: /health/live
      interval_seconds: 30
      
    readiness:
      path: /health/ready
      interval_seconds: 10

# Cost optimization
cost_optimization:
  auto_scaling:
    enabled: true
    min_instances: 1
    max_instances: 10
    target_cpu_percent: 70
    
  data_tiering:
    enabled: true
    hot_data_days: 7
    warm_data_days: 30
    cold_storage: true
    
  regional_distribution:
    optimize_for_cost: true
    prefer_regions: [us-west-2, us-east-1]