from fastapi import FastAPI

app = FastAPI(title="PRP Agent", version="1.0.0")

@app.get("/")
async def root():
    return {"message": "PRP Agent - Running on port 5678!"}

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "prp-agent"}

@app.get("/docs")
async def custom_swagger_ui_html():
    return {"message": "Documentation available at /docs (auto-generated by FastAPI)"}